# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-09 21:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='img/')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('pdf', models.FileField(upload_to='pdf/')),
                ('image', models.ImageField(upload_to='img/')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='img/')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('pdf', models.FileField(upload_to='pdf/')),
                ('image', models.ImageField(upload_to='img/')),
            ],
        ),
        migrations.CreateModel(
            name='SupportService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='super_services', to='impresos.Service')),
                ('subservice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supported_services', to='impresos.Service')),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='subservices',
            field=models.ManyToManyField(through='impresos.SupportService', to='impresos.Service'),
        ),
    ]
