# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-12 16:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('impresos', '0003_auto_20161010_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='impresos.ProductCategory'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_categories', to='impresos.Area'),
        ),
    ]
